server:
  port: 8686
  servlet:
    context-path: /api
#  数据库
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xztx?serverTimezone=UTC
    username: root
    password: zzj0806
  jackson:
    time-zone: GMT+8
  # redis 配置
  redis:
    # 地址
    host: xxxxx
    # 端口，默认为6379
    port: 6379
    # 密码，密码用双引号括起来，血与泪的排查（重置服务器的代价）
    password: "0806"
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
    database: 1
  #接口文档报错
  mvc:
    path match:
      matching-strategy:  ANT_PATH_MATCHER
#session失效時間
  session:
    timeout: 86400
    store-type: redis
#逻辑删除
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


